### ISSUE TITLE
1.9: query_object_type needs to be optional in Affiliate_WP_DB

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1619]
See https://github.com/AffiliateWP/affiliatewp-direct-link-tracking/issues/51

The `query_object_type` property was added to `Affiliate_WP_DB` as part of #1184. The Direct Link Tracking add-on, and possibly others, extend the `Affiliate_WP_DB` class. The problem is that the DB classes now depend on there being associated objects, which will not exist for any add-on that already extends the base class.

We need to make `query_object_type` and the reliance on core objects optional to ensure we aren't breaking backwards compatibility.

**Comment by DrewAPicture** [comment]
Added a PR: #1620

**Comment by pippinsplugins** [comment]
@DrewAPicture that doesn't seem to fix it for me.

Steps to replicate:

1. Activate DLT
2. Go to Affiliates table and click Edit on one
3. Add a URL to the affiliate
4. Click Update and go back to affiliates table
5. Status will now be blank in table

**Comment by DrewAPicture** [comment]
@pippinsplugins Any new errors? The fatal should now be gone.

**Comment by DrewAPicture** [comment]
@pippinsplugins The affiliate status bug was unrelated to DLT as far as I can tell. It's been fixed in the PR. We were defaulting to an empty value if a value isn't passed, which is obviously wrong. The fix defaults to the current status.

**Comment by pippinsplugins** [comment]
@DrewAPicture ok well it still happens to me even on the PR branch.

**Comment by sumobi** [comment]
@DrewAPicture @pippinsplugins 

I can confirm that this PR seems to fix the status issue with DLT 👍  

You can replicate the original issue by just saving the edit affiliate screen, no need to enter a domain.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Works for me now too. Merging and closing.
